from enum import Enum

class TokenType(Enum):
    PACKAGE = "PACKAGE"
    IMPORT = "IMPORT"
    FUNC = "FUNC"
    STRUCT = "STRUCT"
    INTERFACE = "INTERFACE"
    TYPE = "TYPE"
    VAR = "VAR"
    CONST = "CONST"
    IF = "IF"
    ELSE = "ELSE"
    FOR = "FOR"
    RANGE = "RANGE"
    RETURN = "RETURN"
    DEFER = "DEFER"
    GO = "GO"
    CHAN = "CHAN"
    MAP = "MAP"
    SELECT = "SELECT"
    SWITCH = "SWITCH"
    CASE = "CASE"
    DEFAULT = "DEFAULT"
    BREAK = "BREAK"
    CONTINUE = "CONTINUE"
    GOTO = "GOTO"
    FALLTHROUGH = "FALLTHROUGH"
    TRUE = "TRUE"
    FALSE = "FALSE"
    NIL = "NIL"
    UNDERSCORE = "_"  
    CARET = "^"
    

    ASSIGN = "="
    DEFINE = ":="  
    PLUS = "+"
    MINUS = "-"
    BANG = "!"
    ASTERISK = "*"
    SLASH = "/"
    PERCENT = "%"
    LT = "<"
    GT = ">"
    LTE = "<="
    GTE = ">="
    EQ = "=="
    NOT_EQ = "!="
    AND = "&&"
    OR = "||"
    ARROW = "<-"  
    PLUS_PLUS = "++"
    MINUS_MINUS = "--"
    LEFT_PAREN = "("
    RIGHT_PAREN = ")"
    LEFT_BRACE = "{"
    RIGHT_BRACE = "}"
    LEFT_BRACKET = "["
    RIGHT_BRACKET = "]"
    COMMA = ","
    SEMICOLON = ";"
    COLON = ":"
    DOT = "."
    AMPERSAND = "&"
    ELLIPSIS = "..."
    
    PLUS_ASSIGN = "+="
    MINUS_ASSIGN = "-="
    STAR_ASSIGN = "*="
    SLASH_ASSIGN = "/="
    PERCENT_ASSIGN = "%="
    AMP_ASSIGN = "&="
    OR_ASSIGN = "|="
    CARET_ASSIGN = "^="
    SHIFT_LEFT_ASSIGN = "<<="
    SHIFT_RIGHT_ASSIGN = ">>="
    AND_NOT_ASSIGN = "&^="

    BIT_AND = "&"
    BIT_OR = "|"
    BIT_XOR = "^" 
    BIT_CLEAR = "&^" 
    SHIFT_LEFT = "<<"
    SHIFT_RIGHT = ">>"

    IDENT = "IDENT"      
    INT = "INT"
    FLOAT = "FLOAT"
    STRING = "STRING"

    COMMENT = "COMMENT"    
    EOF = "EOF"